defaultName: DeviceExplorer

iotHub:
 hostName: DemoIotHubTecho.azure-devices.net
 sharedAccessKeyName: iothubowner
 sharedAccessKey: Isf6fOl7GPidcWws1/xpOHSUS8ngxKKlcKiOnnk6eV0=
#iotHub:
# hostName: birlasoftrial2.azure-devices.net
# sharedAccessKeyName: iothubowner
# sharedAccessKey: mfBZLsKD8x6zxRNZ6dN4QAm6g9JB6Ly+fkYk7aLJIDc=

maxShowDeviceCount: 100
